import Head from "next/head";
import "./globals.css";
import Logo from "../assets/logo (4).png";
export const metadata = {
  title: "SpeedyTow",
  description: "Generated by Next.js",
  icons: [{ rel: "icon", url: Logo.src }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
